### ISSUE TITLE
配置好的环境我在linux上应该如何使用？

### ISSUE THREAD

**Issue by mingyangD** [KajiMaCN/CRPGCN#3]
希望给出安装命令和操作，新手小白第一次接触，正在学习ing...

**Comment by mingyangD** [comment]
应为有个包pyrwr始终装不上，所以我从网盘上下载了你配置好的环境。但是光下载好我不会用...希望您能指导一下，万分感谢！！！

**Comment by KajiMaCN** [comment]
你好，如果你使用的是图形界面的pyCharm，请按照以下步骤点击按钮：
File->Setting->Project:CRPGCN-master->点击串口右边设置齿轮按钮->Add->Virtualenv Environment->Existing environment->点击...按钮->选择下载环境文件目录下的python.exe文件->一路点击OK。

**Comment by huangyueshiqi** [comment]
谢谢你的详细解答，对我很有帮助。但我遇到了前面一样的问题：pyrwr包安装不了，我猜测这是一个用于RWR的包吗？为什么会安装不上呢，而且网上也没有搜到相关信息，希望您能解答一下，谢谢！

**Comment by KajiMaCN** [comment]
> 谢谢你的详细解答，对我很有帮助。但我遇到了前面一样的问题：pyrwr包安装不了，我猜测这是一个用于RWR的包吗？为什么会安装不上呢，而且网上也没有搜到相关信息，希望您能解答一下，谢谢！

请遵循此项开源代码安装流程：[pyrwr](https://github.com/jinhongjung/pyrwr)
需要将源码下载到本地安装

**Comment by huangyueshiqi** [comment]
谢谢你及时的回复，我现在已经可以运行代码了。非常感谢！

**Comment by KajiMaCN** [comment]
> 谢谢你及时的回复，我现在已经可以运行代码了。非常感谢！

不客气，祝科研顺利^^
