### ISSUE TITLE
咨询问题

### ISSUE THREAD

**Issue by lsgdsg** [KajiMaCN/CRPGCN#5]
你好，可以留个联系方式吗，有两个问题想请教一下，感谢感谢了

**Comment by lsgdsg** [comment]
您好，就是您的项目里面的数据集RNA-sim和Disease-sim是已经融合了相似性后的综合相似性是吧？就是我想问一下您有没有单独的CircRNA序列相似性和疾病语义相似性呢？非常感谢，期待您的回复谢谢！

**Comment by KajiMaCN** [comment]
> 您好，就是您的项目里面的数据集RNA-sim和Disease-sim是已经融合了相似性后的综合相似性是吧？就是我想问一下您有没有单独的CircRNA序列相似性和疾病语义相似性呢？非常感谢，期待您的回复谢谢！

你好，应该是有的，不过我要找一下，请在此留下邮箱

**Comment by lsgdsg** [comment]
真的非常感谢，谢谢！1633726416@qq.com
